---
title: "Consent Searches + Force Originating in Low Level Offense"
author: "Allison Tielking"
date: "2/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Libraries
library(tidyverse)
options(scipen=999)
```


```{r message=FALSE, warning=FALSE}
# Parameters
head(RIPA.Stop.Data.2018)

RIPA_annotated <- RIPA.Stop.Data.2018 %>% select (-c(G_FEMALE, G_GENDER_NONCONFORMING, G_MALE, G_TRANSGENDER_MAN, G_TRANSGENDER_WOMAN, G_FULL, G_MULTIGENDER)) %>% select(1:14, GENDER, everything()) %>% mutate(ADS_SEARCH_PERSON = replace_na(ADS_SEARCH_PERSON, 0)) %>% mutate(ADS_SEARCH_PROPERTY = replace_na(ADS_SEARCH_PROPERTY, 0)) %>% mutate(BFS_CONSENT_GIVEN = replace_na(BFS_CONSENT_GIVEN, 0)) %>% mutate(BFS_OFFICER_SAFETY = replace_na(BFS_OFFICER_SAFETY, 0)) %>% mutate(BFS_SEARCH_WARRANT = replace_na(BFS_SEARCH_WARRANT, 0)) %>% mutate(BFS_PAROLE = replace_na(BFS_PAROLE, 0)) %>% mutate(BFS_SUSPECT_WEAPON = replace_na(BFS_SUSPECT_WEAPON, 0)) %>% mutate(BFS_VISIBLE_CONTRABAND = replace_na(BFS_VISIBLE_CONTRABAND, 0)) %>% mutate(BFS_ODOR_CONTRABAND = replace_na(BFS_ODOR_CONTRABAND, 0)) %>% mutate(BFS_CANINE_DETECT = replace_na(BFS_CANINE_DETECT, 0)) %>% mutate(BFS_EVIDENCE = replace_na(BFS_EVIDENCE, 0)) %>% mutate(BFS_INCIDENT = replace_na(BFS_INCIDENT, 0)) %>% mutate(BFS_EXIGENT_CIRCUM = replace_na(BFS_EXIGENT_CIRCUM, 0)) %>% mutate(BFS_VEHICLE_INVENT = replace_na(BFS_VEHICLE_INVENT, 0)) %>% mutate(BFS_SCHOOL_POLICY = replace_na(BFS_SCHOOL_POLICY, 0))

head(RIPA_annotated)
```


```{r message=FALSE, warning=FALSE}
RIPA_consent_no_gun <- RIPA_annotated %>% group_by(AGENCY_NAME) %>% mutate(count = 1) %>% mutate(count_search = ifelse(ADS_SEARCH_PERSON == 1 |  ADS_SEARCH_PROPERTY == 1, 1, 0)) %>% mutate(count_search_consent = ifelse(count_search == 1 & (BFS_CONSENT_GIVEN == 1 & BFS_OFFICER_SAFETY == 0 & BFS_SEARCH_WARRANT == 0 & BFS_PAROLE == 0 & BFS_SUSPECT_WEAPON == 0 & BFS_VISIBLE_CONTRABAND == 0 & BFS_ODOR_CONTRABAND == 0 & BFS_CANINE_DETECT == 0 & BFS_EVIDENCE == 0 & BFS_INCIDENT == 0 & BFS_EXIGENT_CIRCUM == 0 & BFS_VEHICLE_INVENT == 0 & BFS_SCHOOL_POLICY == 0), 1, 0)) %>% mutate(contraband_count = ifelse(CED_NONE_CONTRABAND == 0 & count_search == 1, 1, 0)) %>% mutate(contraband_no_gun_count = count_search_consent == 1 & CED_FIREARM == 0) %>% mutate(consent_search_no_weapon_count = contraband_no_gun_count == 1 & count_search_consent == 1) %>% summarize(
  STOP_COUNT = sum(count),
  SEARCH_COUNT = sum(count_search),
  SEARCH_CONSENT_COUNT = sum(count_search_consent),
  CONTRABAND_COUNT = sum(contraband_count),
  CONSENT_SEARCH_NO_GUN_COUNT = sum(contraband_no_gun_count),
  CONSENT_SEARCH_NO_GUN_RATE = (CONSENT_SEARCH_NO_GUN_COUNT / SEARCH_CONSENT_COUNT) * 100
) %>% select(-c(SEARCH_COUNT, STOP_COUNT))

write_csv(RIPA_consent_no_gun, path="./RIPA_consent_no_gun.csv")

```

```{r message=FALSE, warning=FALSE}
RIPA_ban_pretext_impact <- RIPA_annotated %>% group_by(AGENCY_NAME) %>% mutate(count = 1) %>% mutate(count_search = ifelse(ADS_SEARCH_PERSON == 1 |  ADS_SEARCH_PROPERTY == 1, 1, 0)) %>% mutate(count_search_consent = ifelse(count_search == 1 & (BFS_CONSENT_GIVEN == 1 & BFS_OFFICER_SAFETY == 0 & BFS_SEARCH_WARRANT == 0 & BFS_PAROLE == 0 & BFS_SUSPECT_WEAPON == 0 & BFS_VISIBLE_CONTRABAND == 0 & BFS_ODOR_CONTRABAND == 0 & BFS_CANINE_DETECT == 0 & BFS_EVIDENCE == 0 & BFS_INCIDENT == 0 & BFS_EXIGENT_CIRCUM == 0 & BFS_VEHICLE_INVENT == 0 & BFS_SCHOOL_POLICY == 0), 1, 0)) %>% mutate(arrest_count = ifelse(ROS_CUSTODIAL_WITHOUT_WARRANT == 1, 1, 0)) %>% mutate(use_of_force_count = ifelse(ADS_FIREARM_POINT == 1 | ADS_FIREARM_DISCHARGE == 1 | ADS_BATON == 1 | ADS_CHEM_SPRAY == 1 | ADS_IMPACT_DISCHARGE == 1 | ADS_CANINE_BITE == 1 | ADS_ELECT_DEVICE == 1 | ADS_OTHER_CONTACT == 1, 1, 0)) %>% mutate(use_of_force_count = ifelse(is.na(use_of_force_count), 0, use_of_force_count)) %>% mutate(firearm_discharge_count = ifelse(ADS_FIREARM_DISCHARGE == 1, 1, 0)) %>% mutate(firearm_discharge_count = ifelse(is.na(firearm_discharge_count), 0, firearm_discharge_count)) %>% mutate(arrest_count_ban_pretext = ifelse(arrest_count == 1 & count_search_consent == 0, 1, 0)) %>% mutate(force_count_ban_pretext = ifelse(use_of_force_count == 1 & count_search_consent == 0, 1, 0)) %>% mutate(firearm_discharge_count_ban_pretext = ifelse(firearm_discharge_count == 1 & count_search_consent == 0, 1, 0)) %>% summarize(
  STOP_COUNT = sum(count),
  SEARCH_CONSENT_COUNT = sum(count_search_consent),
  ARREST_COUNT = sum(arrest_count) * 2,
  ARREST_COUNT_BAN_PRETEXT = sum(arrest_count_ban_pretext) * 2,
  IMPACT_PEOPLE_ARREST_BAN_YEAR = (ARREST_COUNT - ARREST_COUNT_BAN_PRETEXT) * 2,
  PERCENT_DIFF_ARREST_BAN = ((ARREST_COUNT_BAN_PRETEXT - ARREST_COUNT) / ARREST_COUNT) * 100,
  USE_FORCE_COUNT = sum(use_of_force_count) * 2,
  USE_FORCE_COUNT_BAN_PRETEXT = sum(force_count_ban_pretext) * 2,
  IMPACT_PEOPLE_FORCE_BAN_YEAR = (USE_FORCE_COUNT - USE_FORCE_COUNT_BAN_PRETEXT) * 2,
  PERCENT_DIFF_FORCE_BAN = ((USE_FORCE_COUNT_BAN_PRETEXT - USE_FORCE_COUNT) / USE_FORCE_COUNT) * 100,
  FIREARM_DISCHARGE_COUNT = sum(firearm_discharge_count) * 2,
  FIREARM_DISCHARGE_COUNT_BAN_PRETEXT = sum(firearm_discharge_count_ban_pretext) * 2,
  IMPACT_PEOPLE_GUNSHOT_BAN_YEAR = (FIREARM_DISCHARGE_COUNT - FIREARM_DISCHARGE_COUNT_BAN_PRETEXT) * 2,
  PERCENT_DIFF_FIREARM_DISCHARGE_BAN = ((FIREARM_DISCHARGE_COUNT_BAN_PRETEXT - FIREARM_DISCHARGE_COUNT) / FIREARM_DISCHARGE_COUNT) * 100
) %>% select(c(AGENCY_NAME, contains("IMPACT")))

write_csv(RIPA_ban_pretext_impact, path="./RIPA_ban_pretext_impact.csv")

```

```{r message=FALSE, warning=FALSE}

RIPA_annotated$STOP_CODE <- paste(RIPA_annotated$ROS_WARNING_CDS,RIPA_annotated$ROS_CITATION_CDS,RIPA_annotated$ROS_IN_FIELD_CITE_RELEASE_CDS,RIPA_annotated$ROS_CUSTODIAL_WOUT_WARRANT_CDS,sep=",")

RIPA_force_counts <- RIPA_annotated %>% mutate(count = 1) %>% mutate(use_of_force_count = ifelse(ADS_FIREARM_POINT == 1 | ADS_FIREARM_DISCHARGE == 1 | ADS_BATON == 1 | ADS_CHEM_SPRAY == 1 | ADS_IMPACT_DISCHARGE == 1 | ADS_CANINE_BITE == 1 | ADS_ELECT_DEVICE == 1 | ADS_OTHER_CONTACT == 1, 1, 0)) %>% mutate(firearm_discharge_count = ifelse(ADS_FIREARM_DISCHARGE == 1, 1, 0)) %>% mutate(use_of_force_count = ifelse(is.na(use_of_force_count), 0, use_of_force_count)) %>% mutate(firearm_discharge_count = ifelse(is.na(firearm_discharge_count), 0, firearm_discharge_count)) %>% select(c(AGENCY_NAME, STOP_CODE, PERSON_NUMBER, contains("count"), DOJ_RECORD_ID))

# RIPA_force_counts %>% distinct(DOJ_RECORD_ID, AGENCY_NAME, PERSON_NUMBER)
# RIPA_force_counts %>% group_by(AGENCY_NAME) %>% count(use_of_force_count)

RIPA_annotated_codes <- RIPA_force_counts %>% mutate(STOP_CODE = strsplit(as.character(STOP_CODE), ",")) %>% unnest_legacy(STOP_CODE) %>% mutate(STOP_CODE = as.numeric(STOP_CODE)) %>% mutate(STOP_CODE = ifelse(is.na(STOP_CODE), -1, STOP_CODE))

RIPA_join_cds <- left_join(RIPA_annotated_codes, CDS_Codes, by=c("STOP_CODE"="CDS.Code")) %>% select(-c(STOP_CODE, Offense.Description)) %>% mutate(Offense.Level = ifelse(Offense.Level == "M", "Misdemeanor", "Other")) %>% mutate(Offense.Level = ifelse(is.na(Offense.Level), "Other", Offense.Level)) %>% arrange(AGENCY_NAME, DOJ_RECORD_ID, Offense.Level) %>% distinct(DOJ_RECORD_ID, AGENCY_NAME, PERSON_NUMBER, .keep_all = TRUE)

# RIPA_join_cds %>% group_by(AGENCY_NAME) %>% count(Offense.Level)

RIPA_force_low_level <- RIPA_join_cds %>% mutate(force_originate_low_level_count = ifelse(Offense.Level == "Low-Level" & use_of_force_count == 1, 1, 0)) %>% mutate(gunshot_originate_low_level_count = ifelse(Offense.Level == "Low-Level" & firearm_discharge_count == 1, 1, 0)) %>% group_by(AGENCY_NAME) %>% summarise(
  FORCE_COUNT = sum(use_of_force_count),
  FIREARM_DISCHARGE_COUNT = sum(firearm_discharge_count),
  FORCE_ORIGINATE_LOW_LEVEL_COUNT = sum(force_originate_low_level_count),
  GUNSHOT_ORIGINATE_LOW_LEVEL_COUNT = sum(gunshot_originate_low_level_count),
  PERCENT_FORCE_ORIGINATE_LOW_LEVEL = (FORCE_ORIGINATE_LOW_LEVEL_COUNT / FORCE_COUNT) * 100,
  PERCENT_GUNSHOT_ORIGINATE_LOW_LEVEL = ifelse(FIREARM_DISCHARGE_COUNT == 0, 0, (GUNSHOT_ORIGINATE_LOW_LEVEL_COUNT / FIREARM_DISCHARGE_COUNT) * 100)
)

write_csv(RIPA_force_low_level, path="./RIPA_force_low_level.csv")


```
