---
title: "Significance Dataset Generator"
author: "Allison Tielking"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
head(RIPA.Stop.Data.2018)

RIPA.Stop.Data.2018$RACE <- 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 1, "Asian",
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 2, "Black", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 3, "Hispanic", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 4, "Asian", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 8, "Multiracial", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 5, "Native American", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 6, "Pacific Islander", "White")))))))

# Select only relevant cols
RIPA_r <- RIPA.Stop.Data.2018 %>% 
  select(-starts_with('RAE_')) %>% 
  select(1:13, RACE, everything()) %>%
  select(AGENCY_NAME, RACE, ROS_CUSTODIAL_WITHOUT_WARRANT, ROS_CUSTODIAL_WOUT_WARRANT_CDS)

# Convert and join arrest codes, calc offense counts 
RIPA_arrest_codes <- RIPA_r[!(RIPA_r$ROS_CUSTODIAL_WOUT_WARRANT_CDS == " ") , ] %>%
  mutate(ROS_CUSTODIAL_WOUT_WARRANT_CDS = strsplit(as.character(ROS_CUSTODIAL_WOUT_WARRANT_CDS), ", ")) %>%
  unnest_legacy(ROS_CUSTODIAL_WOUT_WARRANT_CDS) %>%
  mutate(ROS_CUSTODIAL_WOUT_WARRANT_CDS = as.numeric(ROS_CUSTODIAL_WOUT_WARRANT_CDS)) 

RIPA_arrest_join_code <- 
  RIPA_arrest_codes %>% 
  inner_join(CDS_Codes, by = c("ROS_CUSTODIAL_WOUT_WARRANT_CDS" = "CDS.Code")) 
```

```{r message=FALSE, warning=FALSE}
#uh <-
#  RIPA_r %>%
  #select(-matches("ROS_CUSTODIAL_WITHOUT_WARRANT")) %>%
#  mutate(ROS_CUSTODIAL_WOUT_WARRANT_CDS = as.numeric(ROS_CUSTODIAL_WOUT_WARRANT_CDS)) %>%
#  full_join(RIPA_arrest_join_code)

simplified_ripa_black <- RIPA_arrest_join_code %>% 
  filter (AGENCY_NAME == "SAN FRANCISCO PD - DOC" & (RACE == "Black" | RACE == "White")) %>% 
  select(AGENCY_NAME, RACE, ROS_CUSTODIAL_WOUT_WARRANT_CDS) %>%  
  mutate(ROS_CUSTODIAL_WOUT_WARRANT_CDS = as.numeric(ROS_CUSTODIAL_WOUT_WARRANT_CDS))

simplified_ripa_black_codes <- left_join(simplified_ripa_black, CDS_Codes, by=c("ROS_CUSTODIAL_WOUT_WARRANT_CDS"="CDS.Code")) %>% 
  select(-c(Offense.Level, ROS_CUSTODIAL_WOUT_WARRANT_CDS)) %>% 
  rename(OFFENSE = Offense.Description)

simplified_ripa_hispanic <- RIPA_arrest_join_code %>% 
  filter (AGENCY_NAME == "SAN FRANCISCO PD - DOC" & (RACE == "Hispanic" | RACE == "White")) %>% 
  select(AGENCY_NAME, RACE, ROS_CUSTODIAL_WOUT_WARRANT_CDS) %>%  
  mutate(ROS_CUSTODIAL_WOUT_WARRANT_CDS = as.numeric(ROS_CUSTODIAL_WOUT_WARRANT_CDS))

simplified_ripa_hispanic_codes <- left_join(simplified_ripa_hispanic, CDS_Codes, by=c("ROS_CUSTODIAL_WOUT_WARRANT_CDS"="CDS.Code")) %>% 
  select(-c(Offense.Level, ROS_CUSTODIAL_WOUT_WARRANT_CDS)) %>% 
  rename(OFFENSE = Offense.Description)

RIPA_r_black_white <- RIPA_r %>%
  filter(AGENCY_NAME == "SAN FRANCISCO PD - DOC" & (RACE == "Black" | RACE == "White"))

codes_non_felonies <- CDS_Codes %>%
  filter(Offense.Level != 'F')

write_csv(simplified_ripa_hispanic_codes, path="../ripa_sf_hispanic_arrest.csv")
write_csv(simplified_ripa_black_codes, path="../ripa_sf_black_arrest.csv")
write_csv(RIPA_r_black_white, path="../RIPA_r_black_white.csv")
write_csv(codes_non_felonies, path ="./CDS_Codes_non_felonies.csv")

```



```{r message=FALSE, warning=FALSE}
RIPA.Stop.Data.2018$RACE <- 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 1, "Asian",
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 2, "Black", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 3, "Hispanic", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 4, "Asian", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 8, "Multiracial", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 5, "Native American", 
  ifelse(RIPA.Stop.Data.2018$RAE_FULL == 6, "Pacific Islander", "White")))))))

RIPA.Stop.Data.2018 %>% distinct(AGENCY_NAME)
# Select only relevant cols
RIPA_r_arrest <- RIPA.Stop.Data.2018 %>% 
  select(-starts_with('RAE_')) %>% 
  select(1:13, RACE, everything()) %>%
  select(AGENCY_NAME, RACE, ROS_CUSTODIAL_WITHOUT_WARRANT)

simplified_ripa_black <- RIPA_r_arrest %>% 
  filter (AGENCY_NAME == "LOS ANGELES CO SD" & (RACE == "Black" | RACE == "White"))

simplified_ripa_hispanic <- RIPA_r_arrest %>% 
  filter (AGENCY_NAME == "LOS ANGELES CO SD" & (RACE == "Hispanic" | RACE == "White"))

write_csv(simplified_ripa_hispanic, path="../arrest_sig/ripa_sdpd_hispanic_arrest.csv")
write_csv(simplified_ripa_black, path="../arrest_sig/ripa_sdpd_black_arrest.csv")
```
